### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by mossheim**
• split up some methods that test multiple concepts
• remove usage of waits and syncs (bootServer(s) already syncs)
• reduce specially named servers (this is not a pattern followed elsewhere)
• add setUp and tearDown to TestServer_clientID (reduces duplication even though sometimes redundant)
• add TODO for test that doesn't belong in TestServer_clientID_booted
• rename TestServer_clientIDBooted.sc and TestServerClientID.sc to match the name of the contained class
• in test_fourWaysToPlaySound: simplified logic, stop Pbind player when done, add comments
• in test_allocWhileBooting: remove boot timeout timer, redundant given other tests, replace while loop with do
• standardize name of test (test_Volume -> test_volume)
• move line Ndef.dictFor(s).clear above s.quit to avoid warning message from server

### CODE REVIEW

**Review by adcxyz — CHANGES_REQUESTED** [review]
hey brian, thanks a lot for cleaning these up, 
almost everything looks good! 
Only 2 changes please:
1. the whole point of test_allocWhileBooting is to check that in the booting process, one can never create duplicate nodeIDs once server.serverRunning is true (i.e. the nodeAllocators will not be reset after this point).
this requires s.boot, and the waiting loop;
with this.bootServer(s) you make the test too easy, and actually bypass the point of the test.
2. fourWaysToPlaysound tests that with typical user code (s.waitForBoot), the four most common ways of crating sound processes will work. 
UnitTest.bootServer(s) is not user code, and too well-bahaved compared to waitForBoot, so again, the test becomes too easy here.

**Comment by mossheim** [comment]
@adcxyz done, let me know if there are any issues with what i just pushed

**Comment by adcxyz** [comment]
looks good now, thanks!!

**Comment by adcxyz** [comment]
just tested running this by hand 20 times, no more node not founds!
```
fork { 
	u = TestServer_boot.new;
		u.setUp;
		u.test_waitForBoot_fourWaysToPlaySound;
		0.5.wait;
		u.tearDown;
};
```

**Comment by adcxyz** [comment]
... and these also run fine repeatedly, so it looks good - thanks @brianlheim!
```
TestServer_boot.run;
TestServer_clientID.run;
TestServer_clientID_booted.run;
```

**Comment by mossheim** [comment]
Thank you!

**Pull request merged**
